inicio
	Inteiro N
	Escreva "Digite um número: "
	Leia N
	Escolha N
	Caso 1:
		Escreva "Janeiro."
	Caso 2:
		Escreva "Fevereiro."
	Caso 3:
		Escreva "Março."
	Caso 4:
		Escreva "Abril."
	Caso 5:
		Escreva "Maio."
	Caso 6:
		Escreva "Junho."
	Caso 7:
		Escreva "Julho."
	Caso 8:
		Escreva "Agosto."
	Caso 9:
		Escreva "Setembro."
	Caso 10:
		Escreva "Outubro."
	Caso 11:
		Escreva "Novembro."
	Caso 12:
		Escreva "Dezembro."
	Defeito:
		Escreva "Inválido."
	Fimescolha
fimalgoritmo