inicio
	Escreva "================================ DADOS PESSOAIS ================================ \n"
	Escreva "Nome completo: Paulo Manuel da Silva Pessoa \n"
	Escreva "Filiação: Domingos Adão Buambuala José e Cristina José da Silva Miguel Buambuala \n"
	Escreva "Residência: Casa Nº 130 Zona 16 Bairro Ngola Kiluange Sambizanga \n"
	Escreva "Natural de: Rangel \n"
	Escreva "Sexo: Masculino \n"
	Escreva "Data de Nascimento: 10 de Dezembro de 1994 \n"
	Escreva "================================================================================"
fimalgoritmo